In [2]:
# loc : label based selection
#Used to access rows/columns by label (index name or column name).

In [4]:
#.iloc : index based selection
#used to access rows/column by integer index

In [5]:
import pandas as pd

In [6]:
df_missing = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Charlie', 'David', None],
    'Age': [25, 30, None, 22, 28],
    'Score': [85, 90, None, 88, 95]
})

In [9]:
mean_age=df_missing['Age'].mean()


In [ ]:
df_missing.groupby('Name')['Age'].agg(['sum','mean'])

In [7]:
import numpy as np


In [8]:
arr = np.array([1, 2, 3])
print(arr)

[1 2 3]


In [9]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [11]:
arr = np.array((1, 3, 2))
print(arr)

[1 3 2]


In [13]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])


In [17]:
arr2 = arr[:2, ::2]


In [18]:
arr2

array([[-1.,  0.],
       [ 4.,  6.]])